version: '3.6'
services:
  redis-channel:
    image: redis:latest
    networks:
      - rest_test
      
  pg-store:
    image:  postgres:latest
    networks:
      - rest_test

  rest-notifucation:
    image: hsz1273327/js-server:restful_c3
    networks:
      - rest_test
    ports:
      - 3000:3000
    volumes:
      - ./conf:/conf
    command: ./node_modules/.bin/babel-node server/index.js --config /conf/docker-env.json

networks:
  rest_test:
